# Generated by Django 3.1.3 on 2021-02-17 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210216_1837'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
